name: 'Auto Run At 15:00UTC - QQ音乐每日时长'

on:
  schedule:
    - cron: '0 15 * * *'
  # push:
  #   branches: 
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'run QQMusicOnedayTime'
        env:
          QQMUSICONEDAYTIME_DATA: ${{ secrets.QQMUSICONEDAYTIME_DATA }}
        run: |
          chmod +x 自动脚本/QQMusicOnedayTime.sh
          bash 自动脚本/QQMusicOnedayTime.sh