name: 'Auto Run At 00:00UTC'

on:
  schedule:
    - cron: '0 0 * * *'
  # push:
  #   branches: 
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install Requests'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests
      - name: 'run AliyunDrive checkin'
        env:
          ALIYUNDRIVE_REFRESH_TOKEN: ${{ secrets.ALIYUNDRIVE_REFRESH_TOKEN }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python 自动脚本/AliyunDriveDaka.py