name: 'Auto Run At 15:00UTC - QQ音乐每日时长 - 每年运行一次好了'
# 只增加当日时长，但不增加音响力  每年的8月27日0:56UTC执行（8:56）

on:
  schedule:
    - cron: '56 0 27 8 *'
  # push:
  #   branches: 
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'run QQMusicOnedayTime'
        env:
          QQMUSICONEDAYTIME_DATA: ${{ secrets.QQMUSICONEDAYTIME_DATA }}
        run: |
          chmod +x 自动脚本/QQMusicOnedayTime.sh
          bash 自动脚本/QQMusicOnedayTime.sh