name: 'Auto Run At 00:00UTC - 阿里云盘打卡'

on:
  # schedule:
  #   - cron: '0 0 * * *'
  schedule:  # 每年的6月28日2:03UTC执行（10:03）
    - cron: '3 2 28 6 *'
  # push:
  #   branches: 
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install Requests'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests
      - name: 'run AliyunDrive checkin'
        env:
          ALIYUNDRIVE_REFRESH_TOKEN: ${{ secrets.ALIYUNDRIVE_REFRESH_TOKEN }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python 自动脚本/AliyunDriveDaka.py