name: BUCT daka with python

on: 
  schedule:
    - cron: '42 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Requests
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests

    - name: really run
      run: |
        python 自动脚本/疫情防控自动打卡.py
