name: 'RemindToPunchIn'

on:
  schedule:
    - cron: '0 8 * * *' # UTC+8 16:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install Packages'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade bs4
      - name: 'run Reminder'
        env:
          ADDRESS_BUCTDAKA: ${{ secrets.ADDRESS_BUCTDAKA }}
        run: python 自动脚本/IfFinishedLeetcodeDaka.py