name: 'Auto Run At 21:00UTC And When Pulled'

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install Requests'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests
      - name: 'run cf2dns'
        env:
          ADDRESS_BUCTDAKA: ${{ secrets.ADDRESS_BUCTDAKA }}
          AREA_BUCTDAKA: ${{ secrets.AREA_BUCTDAKA }}
          CITY_BUCTDAKA: ${{ secrets.CITY_BUCTDAKA }}
          COOKIE_BUCTDAKA: ${{ secrets.COOKIE_BUCTDAKA }}
          CREATED_BUCTDAKA: ${{ secrets.CREATED_BUCTDAKA }}
          DATAS_BUCTDAKA: ${{ secrets.DATAS_BUCTDAKA }}
          GEOAPIINFO_BUCTDAKA: ${{ secrets.GEOAPIINFO_BUCTDAKA }}
          HEADERS_BUCTDAKA: ${{ secrets.HEADERS_BUCTDAKA }}
          ID_BUCTDAKA: ${{ secrets.ID_BUCTDAKA }}
          PROVINCE_BUCTDAKA: ${{ secrets.PROVINCE_BUCTDAKA }}
          UID_BUCTDAKA: ${{ secrets.UID_BUCTDAKA }}
          USERAGENT_BUCTDAKA: ${{ secrets.USERAGENT_BUCTDAKA }}
          TEST: ${{ secrets.TEST }}
          # TEST_EMPTY: ${{ secrets.TEST_EMPTY }}  这里加上空的没事，但是python执行就不行了
        run: python 自动脚本/BUCTdaka.py