name: Daily Check In
on:
  schedule:
    - cron: '49 8 * * *'


jobs:
  sign_in:
    runs-on: ubuntu-latest
    # 定义系统类型，这里选择Ubuntu
    steps:
    - name: show by echo
      run: |
        echo 'Hello world'
    - name: '[Prepare] Code Check'
      uses: actions/checkout@v2
      # 从该仓库clone代码到虚拟机
    - name: '[Prepare] Set python'
      uses: actions/setup-python@v1
      # 安装python
      with:
        python-version: 3.8
    - name: '[Prepare] Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests
        # 安装需要的python库
    - name: '[Final Main] Check In'
      run: |
        cd 自动脚本
        python 疫情防控自动打卡.py
        # 执行代码
    - name: show by echo2
      run: |
        echo Daily Check In