
name: test1

on:
  push:
    branches: [ master ]




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Requests
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests

    - name: really run
      run: |
        python autorun/BUCTdaka.py

